# Generated by Django 4.2.5 on 2023-12-10 09:53

import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('magic', models.CharField(max_length=200)),
                ('mime', models.CharField(max_length=200)),
                ('md5', models.CharField(max_length=200)),
                ('crc32', models.CharField(max_length=200)),
                ('sha1', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=200)),
                ('sha512', models.CharField(max_length=200)),
                ('ssdeep', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.file')),
            ],
        ),
    ]
