# Generated by Django 4.2.5 on 2023-12-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_comment_user_tag_session_fileuser_filetag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='crc32',
        ),
        migrations.RemoveField(
            model_name='file',
            name='ssdeep',
        ),
    ]
