# Generated by Django 4.2.5 on 2023-12-29 11:52

from django.db import migrations
import vault.utils


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_remove_file_crc32_remove_file_ssdeep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=vault.utils.CustomDateTimeField(auto_now_add=True),
        ),
    ]
