# Generated by Django 5.0 on 2023-12-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_file_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesession',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filesession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='filetag',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='fileuser',
            name='file',
        ),
        migrations.RemoveField(
            model_name='fileuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='FileComment',
        ),
        migrations.DeleteModel(
            name='FileSession',
        ),
        migrations.DeleteModel(
            name='FileTag',
        ),
        migrations.DeleteModel(
            name='FileUser',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
