# Generated by Django 5.0 on 2023-12-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_remove_filesession_file_remove_filesession_session_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_date']},
        ),
    ]
