# Generated by Django 5.0 on 2023-12-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0013_remove_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
