# Generated by Django 5.0 on 2023-12-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_tag_remove_file_tag_file_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
