# Generated by Django 5.0 on 2023-12-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0016_remove_file_tag_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
