# Generated by Django 5.0 on 2024-04-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0019_tag_remove_file_tags_file_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tags',
        ),
    ]
