# Generated by Django 5.0 on 2024-04-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0022_rename_name_tag_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='files',
            field=models.ManyToManyField(related_name='tags', to='vault.file'),
        ),
    ]
