# Generated by Django 5.0.6 on 2024-06-29 10:32

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('vault', '0024_file_tag_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='tag',
        ),
        migrations.AddField(
            model_name='file',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
