# Generated by Django 5.0.6 on 2024-10-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0026_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_role',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
