# Generated by Django 5.1.4 on 2025-02-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0028_file_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('email', 'Email Address'), ('url', 'URL')], max_length=50)),
                ('value', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('files', models.ManyToManyField(related_name='iocs', to='vault.file')),
            ],
        ),
    ]
