# Generated by Django 5.1.4 on 2025-03-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0029_ioc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='true_or_false',
            field=models.BooleanField(default=True),
        ),
    ]
