# Generated by Django 5.2.11 on 2026-02-27 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0032_ioc_new_indicator_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
