# Generated by Django 5.2.11 on 2026-02-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0033_alter_file_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioc',
            name='type',
            field=models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('email', 'Email Address'), ('url', 'URL'), ('bitcoin', 'Bitcoin Address'), ('cve', 'CVE Identifier'), ('registry', 'Registry Key'), ('named_pipe', 'Named Pipe / Mutex'), ('win_persistence', 'Windows Persistence (Run/Services)'), ('scheduled_task', 'Scheduled Task'), ('linux_cron', 'Linux Cron Persistence'), ('systemd_unit', 'Systemd Unit Persistence'), ('macos_launchagent', 'macOS LaunchAgent / LaunchDaemon')], max_length=50),
        ),
    ]
