# Generated by Django 5.2.11 on 2026-03-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0034_add_persistence_ioc_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ioc',
            name='description',
        ),
        migrations.AddField(
            model_name='ioc',
            name='enriched',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ioc',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ioc',
            name='manually_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
