# Generated by Django 5.2.11 on 2026-03-07 14:42

import django.utils.timezone
import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0035_ioc_enrichment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='simhash',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='simhash_input_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[vault.models._validate_profile_image_size]),
        ),
    ]
