# Generated by Django 5.2.11 on 2026-03-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0037_analysis_result_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mb_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
