# Generated by Django 5.2.11 on 2026-03-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0039_comment_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='simhash',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
