# Generated by Django 5.2.12 on 2026-04-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0047_audit_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='vault_audit_action_99e0fc_idx',
            old_name='vault_audit_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='vault_audit_user_id_575e84_idx',
            old_name='vault_audit_user_idx',
        ),
    ]
