# Generated by Django 5.2.12 on 2026-04-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0048_rename_vault_audit_action_idx_vault_audit_action_99e0fc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('file_upload', 'File upload'), ('file_download', 'File download'), ('file_delete', 'File delete'), ('file_fetch_url', 'File fetched from URL'), ('tag_add', 'Tag added'), ('tag_remove', 'Tag removed'), ('comment_add', 'Comment added'), ('vt_enrich', 'VirusTotal enrichment'), ('mb_lookup', 'MalwareBazaar lookup'), ('stix_export', 'STIX export'), ('ioc_delete', 'IOC deleted'), ('ioc_override', 'IOC verdict overridden'), ('ioc_enrich', 'IOC enriched'), ('yara_create', 'YARA rule created'), ('yara_update', 'YARA rule updated'), ('yara_delete', 'YARA rule deleted'), ('account_lockout', 'Account locked out'), ('account_unlock', 'Account unlocked by admin'), ('key_change', 'API key changed'), ('user_create', 'User created'), ('user_update', 'User updated'), ('user_delete', 'User deleted'), ('user_set_password', 'User password set'), ('role_create', 'Role created'), ('role_update', 'Role updated'), ('role_delete', 'Role deleted'), ('backup_run', 'Database backup run'), ('cyberchef_update', 'CyberChef updated')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'timestamp'], name='vault_faile_usernam_180f6e_idx')],
            },
        ),
    ]
