# Generated by Django 5.2.12 on 2026-04-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0049_failed_login_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('password_reset_request', 'Password reset requested'), ('password_reset_confirm', 'Password reset confirmed'), ('file_upload', 'File upload'), ('file_download', 'File download'), ('file_delete', 'File delete'), ('file_fetch_url', 'File fetched from URL'), ('tag_add', 'Tag added'), ('tag_remove', 'Tag removed'), ('comment_add', 'Comment added'), ('vt_enrich', 'VirusTotal enrichment'), ('mb_lookup', 'MalwareBazaar lookup'), ('stix_export', 'STIX export'), ('ioc_delete', 'IOC deleted'), ('ioc_override', 'IOC verdict overridden'), ('ioc_enrich', 'IOC enriched'), ('yara_create', 'YARA rule created'), ('yara_update', 'YARA rule updated'), ('yara_delete', 'YARA rule deleted'), ('account_lockout', 'Account locked out'), ('account_unlock', 'Account unlocked by admin'), ('key_change', 'API key changed'), ('user_create', 'User created'), ('user_update', 'User updated'), ('user_delete', 'User deleted'), ('user_set_password', 'User password set'), ('role_create', 'Role created'), ('role_update', 'Role updated'), ('role_delete', 'Role deleted'), ('backup_run', 'Database backup run'), ('cyberchef_update', 'CyberChef updated'), ('app_update', 'Application updated'), ('app_migrate', 'Database migrated'), ('app_makemigrations', 'Migrations created')], db_index=True, max_length=50),
        ),
    ]
